name: CI

on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        perl: [ '5.20', '5.22', '5.24', '5.26', '5.28',
                '5.30', '5.32', '5.34', '5.36', '5.36-threaded' ]
        # See options here: https://hub.docker.com/_/perl/tags

    runs-on: ubuntu-latest
    name: perl ${{matrix.perl}}
    container: perl:${{matrix.perl}}

    steps:
    - uses: actions/checkout@v3
    - name: Show perl version
      run: |
        perl -v
    - name: Install modules
      run: |
        cpanm --quiet --notest Dist::Zilla
        dzil authordeps | cpanm --quiet --notest
        echo ok1
        dzil listdeps --verbose
        echo ok2
        dzil listdeps | cpanm --quiet --notest
        # We neeed to install Data::Printer from cp_dev2 _after_ (not before) the previous install commands
        #  since those will reinstall Data::Printer with another version
        echo $PWD
        ls
        git clone --single-branch --branch cp_dev2 https://github.com/hakonhagland/Data-Printer.git
        ls
        cd Data-Printer
        cpanm .
        cd ..
    - name: debug
      run: |
        git --version
        which perl
        perl --version
    - name: Build module and execute tests
      env:
        AUTHOR_TESTING: 1
        RELEASE_TESTING: 1
      run: |
        dzil test